### ISSUE TITLE
Question: why is compression disabled by default in the latest version?

### ISSUE THREAD

**Issue by paoliniluis** [aws/amazon-redshift-jdbc-driver#107]
This is a question rather than a issue: why are you disabling the compression in the latest version? I saw many changes in the driver about this and I was wondering if this brought issues either in the driver or in the cluster

**Comment by bhvkshah** [comment]
Hi @paoliniluis thanks for bringing this up! You can also use the Discussion section instead of the Issues section for questions :)

We noticed that the benefits of compression vary depending upon network throughput and how much the returned data compresses. In general, we see performance benefits in lower throughput network environments (e.g, multi-region, customer VPN, etc.). Utilizing compression in higher throughput networks can make performance slightly worse if the overhead of using compression is higher than the time savings of sending less data.

Since we do not know which customers have higher/lower throughput networks, we decided to turn it off by default. Customers are welcome to enable it for their use cases by setting the connection property `compression=lz4`.
